### ISSUE TITLE
Incorrect Wall display fix

### ISSUE THREAD

**Issue by ARWChair** [winstonallo/cub3d#10]
In `draw_texture(t_data *data, int x, t_line line, t_txtr *texture)` fix the fmod. Best value worked for me with `/ 4`. looks the closest to original imo

**Comment by ARWChair** [comment]
I did this `data->hit_pos = fmod(data->hit_pos / 4, data->map_width) / (data->map_width);`

**Comment by winstonallo** [comment]
Will fix, need to also add some kind of flooring for the textures to start at the right section

**Comment by winstonallo** [comment]
Fixed, correct offset was 3.8 (don't ask me why but it's working lol)
